# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: JupyterLite Contributors
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@jupyterlite/cljs-kernel'
project_short_description: ClojureScript kernel for JupyterLite
python_name: jupyterlite_cljs_kernel
repository: https://github.com/jupyterlite/cljs-kernel
test: false

